### ISSUE TITLE
Adding Alternative font-family

### ISSUE THREAD

**Issue by MUDev1994** [aegirzhu/dasmoto#1]
**Bonus**: It is a great idea to have an alternative font-family, just in case the font is not available to our user.

From:
https://github.com/aegirzhu/dasmoto/blob/60c71e50a3b22899161aa854bf4c39288dcb3d65/resources/style.css#L5
To:
```
font-family: "helvetica", sans-serif;
```

**Comment by aegirzhu** [comment]
Thank you Muhammad! I have fixed it in my third commit. Cheers!
