### ISSUE TITLE
Relative images' path

### ISSUE THREAD

**Issue by MUDev1994** [aegirzhu/dasmoto#2]
<h4>Having relative paths to images. </h4>

**What I do I mean?** 
Instead of linking to an outside source like:

https://github.com/aegirzhu/dasmoto/blob/60c71e50a3b22899161aa854bf4c39288dcb3d65/index.html#L13
We would download the images locally in our "resources" => "images" folder (new folder), then link them locally, so the path would look like this:
```
<img src="./images/hacksaw.jpeg" alt="Brushes"> 
```
\
**Why:**
It is better that we have images in our directory. Let's assume we have a website running, and we linked those images somewhere to external URLs. So after a while they took down the images from external site, and now our website will no longer show those images.
\
**Where**
In our case: Index.html file and style.css file

**Comment by aegirzhu** [comment]
Thank you Muhammad! I have downloaded all the images and put them into my local folder and the change has been committed. Thanks for your advice!
