### ISSUE TITLE
SUMMARY

### ISSUE THREAD

**Issue by MUDev1994** [aegirzhu/dasmoto#3]
[Exceeds expectations] Great work!

**Great**

- `alt` tags on images!
- Id names are informative
- Used `<div>` or other similar tags to wrap the section of the code -- Easy to read
- Your CSS code is DRY (Don't Repeat Yourself) 
- Great Indentation in HTML/CSS files
- Consistent space in code
- Added `<title>` tag 👍 
 

**Suggested Improvements**
- Alternative font-family (Bonus) https://github.com/aegirzhu/dasmoto/issues/1
- Images are in "images" directory https://github.com/aegirzhu/dasmoto/issues/2
- Downloaded images to our local images directory and linked them locally https://github.com/aegirzhu/dasmoto/issues/2

Great Job, Well Done! 💯

**Comment by aegirzhu** [comment]
Thanks again for your review! Cheers!
